#spring.h2.console.enabled=true
#spring.h2.console.path=/h2
#spring.datasource.url=jdbc:h2:me
#m:grade-submission

spring:
  datasource:
    url: jdbc:mysql://localhost:24682/jwt_service  # connection link to database
    username: jwt_service
    password: 2017ikedi
    driver-class-name: com.mysql.jdbc.Driver
  jpa:                         # jpa properties
    hibernate:
      ddl-auto: update   # create and destroy the schema when the application stops
    show-sql: true            # when spring JPA performs a query, it should show in console

#    properties:
#      hibernate:
#        format_sql: true
#    database: mysql           # telling JPA that we are using mysql
#    database-platform: org.hibernate.dialect.MySQLDialect
